[tool.black]
line-length = 120
skip-magic-trailing-comma = true
target-version = ['py39']

[tool.isort]
known_first_party = ["ariadne"]
src_paths = ["ariadne"]
line_length = 120
multi_line_output = 3
profile = "black"
py_version = "39"
